version: "3"

services:
  2dpacking:
    build: .
    container_name: "2dpacking"
    ports:
      - "0.0.0.0:7777:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    restart: unless-stopped
